### ISSUE TITLE
Has this webminer servers support been stopped?

### ISSUE THREAD

**Issue by vpts1202** [NajmAjmal/monero-webminer#20]
In your index.html file I have just changed xmr address(replaced to mine).
Then I have opened index.html file and following page appeared:
**Mining...
View mining progress _[here](https://moneroocean.stream/)**_
However on moneroocean page no any signs of progress appeared.
I have kept going testing for 15min, 1hour,6 hours in Chrome, MS Edge, Firefox browsers.

A couple of months ago the same test showed progress.
Since webminer landing page is appearing normally its seems that the issue in one(or both) of your servers.

Please advise
Thanks.

**Comment by helpau** [comment]
@vpts1202 try HTML example from "Use In Other Projects" section. On landing i see error in WSS:
{"identifier":"handshake","pool":"**gulf**.moneroocean.stream:80","login":"4657q4dnsjLWtzeW4XN3wG9swFumWAZB9i1pegTLMxVAQy5E5AE8uif42kkHWcWc9vDcLUmzeCf3pV7mmrJQQqqe84dtASi","password":"GH-XMR","userid":"","version":7}
{"identifier":"error","param":"pool not known"}
Example has other pool address than landing

**Comment by vpts1202** [comment]
I have tried couple of other pools out of top-6, no result either.
Looks like this project support has been stopped, since there is no any feedback to issue from project dev.

I have not been able to find any relatable alternative, so lets hope that someone from the community will get back here, since there is 55 forks/82 stars.

**Comment by Lord1Egypt** [comment]
server = ["wss://?algo=rx/0?jason=gulf.moneroocean.stream:10128";
var pool = "gulf.moneroocean.stream:10128";


good luck

**Comment by vpts1202** [comment]
@Ranamom -many thanks,its very kind.
- is it possible to use the pool other than MoneroOcean?
- is it possible to mine RandomX coin other than Monero?

**Comment by Lord1Egypt** [comment]
yes just test and go ahead 

Simple Pool change: ?jason=Your_Favorite_Pool:PortNr
Edit the index.html and add your favorite coin/algo
Examples: Moneroocean Auto Algo Switch - mining the most profitable coin - XMR Monero Payout | Best choice for mining ;)
(Its working after Monero Hardfork RandomX, if you want xmr payouts)
(CN/CN-Lite/CN-Fast/CN-Half/CN-Pico/CN-RWZ/CN-Heavy:xhv/Argon2id-Chukwa/Argon2id-Chukwav2/Ghostrider/flex)
need ?algo=cn/r
<script src="https://easyhash.de/mmh/mmh.js?perfekt=wss://?algo=cn/r?jason=gulf.moneroocean.stream:10128" > </script>
Examples: CN R Coins (Italocoin, Lethean, Sumokoin) need ?algo=cn/r
<script src="https://easyhash.de/mmh/mmh.js?perfekt=wss://?algo=cn/r?jason=Your_Favorite_Pool:PortNr" > </script>
Examples: CN V8 Reverse Waltz Coins need ?algo=cn/rwz
<script src="https://easyhash.de/mmh/mmh.js?perfekt=wss://?algo=cn/rwz?jason=Your_Favorite_Pool:PortNr" > </script>
Examples: CN | ZLS Coins need ?algo=cn/zls
<script src="https://easyhash.de/mmh/mmh.js?perfekt=wss://?algo=cn/zls?jason=Your_Favorite_Pool:PortNr" > </script>
Examples: CN UPX2 Coins (Uplexa) need ?algo=cn/upx
<script src="https://easyhash.de/mmh/mmh.js?perfekt=wss://?algo=cn/upx?jason=Your_Favorite_Pool:PortNr" > </script>
Examples: CN V8 Coins (Caliber, JyoCoin, PyrexCoin, Safex Cash) need ?algo=cn/2
<script src="https://easyhash.de/mmh/mmh.js?perfekt=wss://?algo=cn/2?jason=Your_Favorite_Pool:PortNr" > </script>
Examples: CN V7 Coins (Beldex, Citadel, CPA Coin, Hospital Coin, LeviarCoin, MoneroV, Mutex, ParsiCoin, Quantum, Superior Coin) need ?algo=cn/1
<script src="https://easyhash.de/mmh/mmh.js?perfekt=wss://?algo=cn/1?jason=Your_Favorite_Pool:PortNr" > </script>
Examples: CN ASIC Coins (B2Bcoin, Balkancoin, BeFrank, Bitcoal, Bold, Bytecoin, Crepcoin, CROAT Coin, DinastyCoin, Discoin, Geem, Incognito, Infinium - 8, Investcoin, InziderX, Karbo, LithiumBit, MonetaVerde, Newton, NinjaCoin, PluraCoin, Qwertycoin, SpesCoin, TFT Network, TycheCash, Video Games, X12 Coin, Xcoin, Xeonbit) need ?algo=cn/0
<script src="https://easyhash.de/mmh/mmh.js?perfekt=wss://?algo=cn/0?jason=Your_Favorite_Pool:PortNr" > </script>
Examples: CN Lite V7 Coins (2ACoin, ADON Coin, BBSCoin, BitcoinNova, BitcoiNote, Bitsum, Bittorium, BytechCoin, Catalyst, Equilibria, IntuCOIN, NashCash, Nibble Classic, Secure Cash, Ultranote, Zent Cash) need ?algo=cn-lite/1
<script src="https://easyhash.de/mmh/mmh.js?perfekt=wss://?algo=cn-lite/1?jason=Your_Favorite_Pool:PortNr" > </script>
Examples: CN Pico Coins (BitcoinMono, Cypruscoin, Dero Gold, ElphyreCoin, HITC, Iridium, LightChain, Mangocoin, Obscure, Oscillate, Plenteum, Tellurium, Tritanium, TurtleGold, Worktips, WrkzCoin, XtendCash) need ?algo=cn-pico/trtl
<script src="https://easyhash.de/mmh/mmh.js?perfekt=wss://?algo=cn-pico/trtl?jason=Your_Favorite_Pool:PortNr" > </script>
Examples: Argon2id - Chukwa Coins need ?algo=chukwa
<script src="https://easyhash.de/mmh/mmh.js?perfekt=wss://?algo=chukwa?jason=Your_Favorite_Pool:PortNr" > </script>
Examples: Argon2id - ChukwaV2 (Turtlecoin) Coins need ?algo=chukwav2
<script src="https://easyhash.de/mmh/mmh.js?perfekt=wss://?algo=chukwav2?jason=Your_Favorite_Pool:PortNr" > </script>
Examples: CN Fast V2 | CN Half Coins (Masari) need ?algo=cn/half
<script src="https://easyhash.de/mmh/mmh.js?perfekt=wss://?algo=cn/half?jason=Your_Favorite_Pool:PortNr" > </script>
Examples: CN Fast Coins (Aluisyo, Electronero, ElectroneroXP) need ?algo=cn/msr
<script src="https://easyhash.de/mmh/mmh.js?perfekt=wss://?algo=cn/msr?jason=Your_Favorite_Pool:PortNr" > </script>
Examples: CN Heavy Classic Coins (Bixbite) need ?algo=cn-heavy/0
<script src="https://easyhash.de/mmh/mmh.js?perfekt=wss://?algo=cn-heavy/0?jason=Your_Favorite_Pool:PortNr" > </script>
Examples: CN Heavy XHV Coins (Haven, BLOC.money, CitiCash, Niobio Cash, Ombre) need ?algo=cn-heavy/xhv
<script src="https://easyhash.de/mmh/mmh.js?perfekt=wss://?algo=cn-heavy/xhv?jason=Your_Favorite_Pool:PortNr" > </script>
Examples: CN-Saber Coins (BitTube) need ?algo=cn-heavy/tube (only valid until 29th July 2020 because of Hardfork to Cuckaroo29b)
<script src="https://easyhash.de/mmh/mmh.js?perfekt=wss://?algo=cn-heavy/tube?jason=Your_Favorite_Pool:PortNr" > </script>
Examples: RandomX as Test algo - proof of concept (Monero, Zephyr) need ?algo=rx/0
<script src="https://easyhash.de/mmh/mmh.js?perfekt=wss://?algo=rx/0?jason=Your_Favorite_Pool:PortNr" > </script>

Good Luck
